### ISSUE TITLE
Termotanque permite cambiar la cantidad de horas

### ISSUE THREAD

**Issue by mppfiles** [UniversidadDelChubut/balance_cero#2]
El termotanque funciona 24 horas, no debe permitir cambiar la cantidad de horas.

**Comment by enzoana** [comment]
Si no te cortan el agua o el gas... jajaja

2011/9/13 mppfiles <
reply@reply.github.com>

**Comment by mppfiles** [comment]
resuelto desde 521ced7afd86f6e1a84b15b463ceac3f97981161
